language: en-US
tone_instructions: >
  Idiomatic Rust suggestions only if they improve correctness, safety, or readability. 
  If no meaningful issues, respond “LGTM.” 
  Mark subjective feedback as non-blocking (nit). 
  Do not use emojis, ascii art, or unrelated content. 
  Limit scope to netrs PRs

reviews:
  profile: chill           
  request_changes_workflow: true 
  high_level_summary: false
  auto_title_instructions: >
    Format as such: [LABEL] <Concise wrap-up of changes>
  review_status: true
  commit_status: true
  suggested_reviewers: true 
  auto_assign_reviewers: true 
  auto_apply_labels: true
  auto_review:
    enabled: true
    auto_incremental_review: false
    ignore_title_keywords: ["WIP", "draft"]
  path_filters:
    - "netrs-core/**"
    - "netrs-ui/**"
    - "!target/**"
  art: false
