language: en-US
tone_instructions: >
  Prefer idiomatic Rust suggestions only when
  they clearly improve correctness, safety, or readability. If there are no
  meaningful issues, say “LGTM” Mark any subjective ideas
  as non-blocking (nit).

reviews:
  profile: chill           
  request_changes_workflow: true 
  high_level_summary: false
  auto_title_instructions: >
    Format as such: [LABEL] <Concise wrap-up of changes>
  review_status: true
  commit_status: true
  suggested_reviewers: true 
  auto_assign_reviewers: true 
  auto_apply_labels: true
  auto_review:
    enabled: true
    auto_incremental_review: false
    ignore_title_keywords: ["WIP", "draft"]
  path_filters:
    - "netrs-core/**"
    - "netrs-ui/**"
    - "!target/**"
  art: false
